### ISSUE TITLE
Job settings - style "Create New Job" as a button

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#10]
![screen shot 2018-02-06 at 5 17 02 pm](https://user-images.githubusercontent.com/25242/35887226-9fd8c444-0b61-11e8-9c28-f89d7d6991aa.png)
Using a button for the "Create New Job" link would add visual consistency

**Comment by cg923** [comment]
It actually is styled as a button, but the styling doesn't work in all browsers.  

As seen in Chrome and Safari:
<img width="774" alt="screen shot 2018-02-06 at 2 33 36 pm" src="https://user-images.githubusercontent.com/28875167/35887909-c94f3dce-0b4a-11e8-9dcc-34f575daacf0.png">
