### ISSUE TITLE
Progress bar for exporting through the UI

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#13]

**Comment by cg923** [comment]
As of yesterday this is already implemented, though simply as updating text:

<img width="788" alt="screen shot 2018-02-06 at 2 36 59 pm" src="https://user-images.githubusercontent.com/28875167/35888044-39570b1a-0b4b-11e8-868d-02f3549f5a6e.png">

Happy to implement an actual progress bar if that's preferred.

**Comment by adamfranco** [comment]
Ah, I didn't see that when I tried running a job today... Is it in prod?

**Comment by cg923** [comment]
Should be, yes.

**Comment by adamfranco** [comment]
Ah. I see it now. Maybe it doesn't work in IE....

**Comment by adamfranco** [comment]
I'm not sure what browser Kathleen was using, but maybe IE.

**Comment by adamfranco** [comment]
One other note: After the archive finished the URL given ended up being wrong and giving a 404.

**Comment by cg923** [comment]
Hmm.  It's a pretty straightforward system.  Zend dumps progress to a txt file and provides a route for reading that file.  Front end makes ajax calls on a regular interval until the process is finished.

I'll look into this, as it seems there are some underlying issues to be addressed.

**Comment by cg923** [comment]
Ah, the snapshot was discarded because nothing had changed.  The URL should link to _latest.html rather than a particular snapshot.

**Comment by cg923** [comment]
Working fine in Microsoft Edge 14-16.  Haven't tested IE 11

**Comment by cg923** [comment]
Confirmed this works in IE 11.
