### ISSUE TITLE
Move the markup testing tool to the admin screen

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#14]
The [markup testing tool](https://github.com/middlebury/coursecatalog_markup) is currently installed at 
http://hammer.middlebury.edu/~afranco/catalog_markup/index.php

It should be made into an admin screen in the catalog proper to live under `/admin` so that it is more easily available for those doing data entry. It should be updated to strip out any javascript and because no data is saved, can be safely exposed without special authorization.

**Comment by adamfranco** [comment]
Hi Cory, sorry for not specifying this earlier, but we should send the text through [`banner_course_Course::convertDescription()`](https://github.com/middlebury/coursecatalog/blob/master/application/library/banner/course/Course.php#L32) so that we only have one copy of the code that does the parsing and conversion. Let me know if you need more detail on this. :-)

**Comment by cg923** [comment]
Oops!  Didn't realize it lived there already, although I suppose that should have been obvious.  Anyway, fixed now.
