### ISSUE TITLE
Saving Archive config has Javascript error in Firefox

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#24]
Saves works fine in Chrome, but are failing in Firefox.
![screen shot 2018-03-14 at 5 03 01 pm](https://user-images.githubusercontent.com/25242/37430806-b4df7a54-27a9-11e8-8fa1-2b5f061d2f85.png)

I added a new courslist section to Arabic when I noticed this error.

**Comment by cg923** [comment]
@adamfranco I'm not currently able to reproduce this issue in development or production.  Is there anything else I should know?

**Comment by adamfranco** [comment]
I'm able to replicate it in development at http://hammer.middlebury.edu/~afranco/catalog/admin/export/1 by loading that URL, making no changes, entering a commit message, then clicking save.

**Comment by cg923** [comment]
Hmm.  Still works fine for me?

**Comment by adamfranco** [comment]
This behavior is consistent in my browser in dev and production. Using the javascript debugger in FF, I was able to trace the issue to this line in `saveJSON()`
![screen shot 2018-03-15 at 1 55 35 pm](https://user-images.githubusercontent.com/25242/37481650-aa6dd3d6-2858-11e8-88eb-28f1d83b45bc.png)

The last element that matches `$('.group')` is from a firefox extension I have install: https://addons.mozilla.org/en-US/firefox/addon/diigo-web-collector/ :-/

While the problem is with my browser extension injecting markup into the page, would it be reasonable to scope the search a bit more, such as using `$('#sections-list .group')` instead of just `$('.group')`?

**Comment by cg923** [comment]
Ahh ok.  Yes, that seems like an easy fix.  I will check the rest of the JS file too and see if I can be more specific in other places to avoid similar conflicts in the future.
