### ISSUE TITLE
Order meeting times by date

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#29]
Bob Cole:

> @afranco a hub UX question for you - a prof was concerned about the presentation of course schedule info on her hub dashboard. See: https://courses.middlebury.edu/hub/miis/202028/icco/8535a
> 
> The schedule presents meeting days and times in reverse order, and also seems to favor the day of the week over month and day. Not sure what the sort order is, but imagine it could be confusing to some who might rely on hub for this info, at start of classes.
> 
> In Banner it looks like this:
> ![Screen Shot 2020-02-06 at 11 03 05 AM](https://user-images.githubusercontent.com/25242/73980287-ec80a100-48fd-11ea-8d72-1f50188699b8.png)
> 
> I can file a ticket, she also indicates that the data for ICCO is correct, but the cross-listed site for the same course is in-correct: https://courses.middlebury.edu/hub/miis/202028/educ/9535a
> 
> So, there's a combination of issues. UX and correct data. Banner info for EDUC 9535 is correct.
> <img width="454" alt="GetAttachmentThumbnail" src="https://user-images.githubusercontent.com/25242/73980377-133ed780-48fe-11ea-9e16-ac3530b94e56.png">

Adam Franco  2:22 PM

> Thanks for reporting this, Bob. That is certainly a complex case. That string is being generated here:
> https://github.com/middlebury/coursecatalog/blob/master/application/library/banner/course/CourseOffering.php#L480-L526
> And here for loading the entries: https://github.com/middlebury/coursecatalog/blob/master/application/library/banner/course/CourseOffering/AbstractSession.php#L268-L310
> Right now these aren’t ordered, but that can change.

**Comment by adamfranco** [comment]
The schedule is now reordered by start-date and I've started the week on Monday.

Before:
![Before](https://user-images.githubusercontent.com/25242/73980734-dd4e2300-48fe-11ea-963d-8d1322148f1a.png)

After: 
![after](https://user-images.githubusercontent.com/25242/73980740-e212d700-48fe-11ea-9fbe-1f3caf93b238.png)

**Comment by beohbe70** [comment]
@adamfranco thanks for the attention on this. When will the re-order sync over with the Hub?

**Comment by adamfranco** [comment]
Thanks for the ping on that. It would have updated tomorrow morning, but I kicked off the update early: https://courses.middlebury.edu/hub/miis/202028/icco/8535a now has the new format.

**Comment by adamfranco** [comment]
The [EDUC 9535a version](https://courses.middlebury.edu/hub/miis/202028/educ/9535a) wasn't updated because this is no longer an enrollable course and no longer in the data feed. It can be deleted [here](https://courses.middlebury.edu/admin/course_hub/missing_sections?field_school_target_id=miis&field_term_code_value=202028), but it does have a Canvas site attached.
