### ISSUE TITLE
Export Config: Separate H1 into two distinct fields

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#5]
Currently the H1 (and H2) has a single entry field with a delimiter for the two pieces of data, the full title and the table-of-contents (TOC) title: 
![screen shot 2018-02-06 at 4 31 39 pm](https://user-images.githubusercontent.com/25242/35885235-38f2912a-0b5b-11e8-9bc0-a9c4dd067eae.png)

This means that formatting instructions are necessary and the Group shows the full string, both adding to visual clutter in the UI.

- [x] Separate the data into two text fields, full title first and TOC text second.
- [x] Drop the formatting instructions
- [x] Title field can have placeholder text like "Full title for section heading".
- [x] TOC text can have placeholder text like "Short title for table-of-contents".
- [x] Change the group title to use only the TOC text, not the full title, for easier scanning of the full config.
- [x] Above changes for H2 as well.

**Comment by cg923** [comment]
This was my original intention.  I ran into issues that were making this take longer than seemed reasonable at the time, but I'd be happy to re-tool it toward this more integrated approach now that other, more important features have been dealt with.

**Comment by cg923** [comment]
Reopening as group renaming has a bug.
