### ISSUE TITLE
Export Config History - Back link should go to previous page

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#6]
Currently the bread-crumb link goes back to the `/admin/export`:
![screen shot 2018-02-06 at 4 39 44 pm](https://user-images.githubusercontent.com/25242/35885640-7ec680b6-0b5c-11e8-9252-498ebd439891.png)

It would be better if it went back to the screen the user just came from, which is the details of a particular configuration like: `/admin/export?config=....`

**Comment by cg923** [comment]
Whoops.  Yes, that was definitely the intended functionality.
